export interface Oficio {
  id: number
  nombre: string
}

export const oficios: Oficio[] = [
  { "id": 1, "nombre": "Abogado" },
  { "id": 2, "nombre": "Actor" },
  { "id": 3, "nombre": "Actuario" },
  { "id": 4, "nombre": "Administrador" },
  { "id": 5, "nombre": "Agente de seguros" },
  { "id": 6, "nombre": "Agente inmobiliario" },
  { "id": 7, "nombre": "Agricultor" },
  { "id": 8, "nombre": "Albañil" },
  { "id": 9, "nombre": "Analista de datos" },
  { "id": 10, "nombre": "Analista financiero" },

  { "id": 11, "nombre": "Animador 2D/3D" },
  { "id": 12, "nombre": "Antropólogo" },
  { "id": 13, "nombre": "Arquero profesional" },
  { "id": 14, "nombre": "Arquitecto" },
  { "id": 15, "nombre": "Artesano" },

  { "id": 16, "nombre": "Astrónomo" },
  { "id": 17, "nombre": "Auxiliar administrativo" },
  { "id": 18, "nombre": "Auxiliar contable" },
  { "id": 19, "nombre": "Azafata" },
  { "id": 20, "nombre": "Bailarín" },

  { "id": 21, "nombre": "Barbero" },
  { "id": 22, "nombre": "Barrendero" },
  { "id": 23, "nombre": "Bibliotecario" },
  { "id": 24, "nombre": "Bioingeniero" },
  { "id": 25, "nombre": "Biólogo" },

  { "id": 26, "nombre": "Bombero" },
  { "id": 27, "nombre": "Camarero" },
  { "id": 28, "nombre": "Caminero" },
  { "id": 29, "nombre": "Cantinero" },
  { "id": 30, "nombre": "Carpintero" },

  { "id": 31, "nombre": "Cartero" },
  { "id": 32, "nombre": "Cerrajero" },
  { "id": 33, "nombre": "Chef" },
  { "id": 34, "nombre": "Chofer" },
  { "id": 35, "nombre": "Cirujano" },

  { "id": 36, "nombre": "Coach deportivo" },
  { "id": 37, "nombre": "Cobrador" },
  { "id": 38, "nombre": "Comerciante" },
  { "id": 39, "nombre": "Community Manager" },
  { "id": 40, "nombre": "Conductor de radio" },

  { "id": 41, "nombre": "Conserje" },
  { "id": 42, "nombre": "Constructor" },
  { "id": 43, "nombre": "Contador" },
  { "id": 44, "nombre": "Coreógrafo" },
  { "id": 45, "nombre": "Corrector de textos" },

  { "id": 46, "nombre": "Costurero" },
  { "id": 47, "nombre": "Cocinero" },
  { "id": 48, "nombre": "Cuidador de ancianos" },
  { "id": 49, "nombre": "Cuidador de niños" },
  { "id": 50, "nombre": "Decorador" },

  { "id": 51, "nombre": "Dentista" },
  { "id": 52, "nombre": "Desarrollador Backend" },
  { "id": 53, "nombre": "Desarrollador Frontend" },
  { "id": 54, "nombre": "Desarrollador Fullstack" },
  { "id": 55, "nombre": "Desarrollador de videojuegos" },

  { "id": 56, "nombre": "Detective privado" },
  { "id": 57, "nombre": "Diagramador" },
  { "id": 58, "nombre": "Dietista" },
  { "id": 59, "nombre": "Diseñador gráfico" },
  { "id": 60, "nombre": "Diseñador industrial" },

  { "id": 61, "nombre": "Diseñador de interiores" },
  { "id": 62, "nombre": "Docente" },
  { "id": 63, "nombre": "Economista" },
  { "id": 64, "nombre": "Editor de video" },
  { "id": 65, "nombre": "Electricista" },

  { "id": 66, "nombre": "Electromecánico" },
  { "id": 67, "nombre": "Empleado de comercio" },
  { "id": 68, "nombre": "Enfermero" },
  { "id": 69, "nombre": "Entomólogo" },
  { "id": 70, "nombre": "Entrenador personal" },

  { "id": 71, "nombre": "Escultor" },
  { "id": 72, "nombre": "Escritor" },
  { "id": 73, "nombre": "Estadístico" },
  { "id": 74, "nombre": "Esteticista" },
  { "id": 75, "nombre": "Estilista" },

  { "id": 76, "nombre": "Farmacéutico" },
  { "id": 77, "nombre": "Feriante" },
  { "id": 78, "nombre": "Físico" },
  { "id": 79, "nombre": "Fisioterapeuta" },
  { "id": 80, "nombre": "Florista" },

  { "id": 81, "nombre": "Fotógrafo" },
  { "id": 82, "nombre": "Freelancer" },
  { "id": 83, "nombre": "Gasista" },
  { "id": 84, "nombre": "Geógrafo" },
  { "id": 85, "nombre": "Geólogo" },

  { "id": 86, "nombre": "Gerente de ventas" },
  { "id": 87, "nombre": "Grabador de audio" },
  { "id": 88, "nombre": "Guía turístico" },
  { "id": 89, "nombre": "Historiador" },
  { "id": 90, "nombre": "Ingeniero civil" },

  { "id": 91, "nombre": "Ingeniero en sistemas" },
  { "id": 92, "nombre": "Ingeniero electrónico" },
  { "id": 93, "nombre": "Ingeniero industrial" },
  { "id": 94, "nombre": "Inspector" },
  { "id": 95, "nombre": "Instalador de redes" },

  { "id": 96, "nombre": "Jardinero" },
  { "id": 97, "nombre": "Joyero" },
  { "id": 98, "nombre": "Juez" },
  { "id": 99, "nombre": "Locutor" },
  { "id": 100, "nombre": "Maestro mayor de obras" },

  { "id": 101, "nombre": "Maestro panadero" },
  { "id": 102, "nombre": "Malabarista" },
  { "id": 103, "nombre": "Marketing digital" },
  { "id": 104, "nombre": "Mecánico" },
  { "id": 105, "nombre": "Médico" },

  { "id": 106, "nombre": "Mensajero" },
  { "id": 107, "nombre": "Minero" },
  { "id": 108, "nombre": "Modelo" },
  { "id": 109, "nombre": "Músico" },
  { "id": 110, "nombre": "Notario" },

  { "id": 111, "nombre": "Nutricionista" },
  { "id": 112, "nombre": "Obrero" },
  { "id": 113, "nombre": "Odontólogo" },
  { "id": 114, "nombre": "Operador de máquinas" },
  { "id": 115, "nombre": "Paleontólogo" },

  { "id": 116, "nombre": "Panadero" },
  { "id": 117, "nombre": "Parrillero" },
  { "id": 118, "nombre": "Pastelero" },
  { "id": 119, "nombre": "Patólogo" },
  { "id": 120, "nombre": "Payaso" },

  { "id": 121, "nombre": "Peluquero" },
  { "id": 122, "nombre": "Periodista" },
  { "id": 123, "nombre": "Pescador" },
  { "id": 124, "nombre": "Pianista" },
  { "id": 125, "nombre": "Pintor" },

  { "id": 126, "nombre": "Plomero" },
  { "id": 127, "nombre": "Policía" },
  { "id": 128, "nombre": "Político" },
  { "id": 129, "nombre": "Profesor de educación física" },
  { "id": 130, "nombre": "Programador" },

  { "id": 131, "nombre": "Psicólogo" },
  { "id": 132, "nombre": "Psiquiatra" },
  { "id": 133, "nombre": "Publicista" },
  { "id": 134, "nombre": "Químico" },
  { "id": 135, "nombre": "Recepcionista" },

  { "id": 136, "nombre": "Repartidor" },
  { "id": 137, "nombre": "Relojero" },
  { "id": 138, "nombre": "Representante de ventas" },
  { "id": 139, "nombre": "Repostero" },
  { "id": 140, "nombre": "Sastre" },

  { "id": 141, "nombre": "Secretario" },
  { "id": 142, "nombre": "Seguridad privado" },
  { "id": 143, "nombre": "Soldador" },
  { "id": 144, "nombre": "Sommelier" },
  { "id": 145, "nombre": "Tatuador" },

  { "id": 146, "nombre": "Taxista" },
  { "id": 147, "nombre": "Telefonista" },
  { "id": 148, "nombre": "Técnico electrónico" },
  { "id": 149, "nombre": "Técnico informático" },
  { "id": 150, "nombre": "Técnico químico" },

  { "id": 151, "nombre": "Tornero" },
  { "id": 152, "nombre": "Traductor" },
  { "id": 153, "nombre": "Transportista" },
  { "id": 154, "nombre": "Tripulante de cabina" },
  { "id": 155, "nombre": "Urólogo" },

  { "id": 156, "nombre": "Vendedor" },
  { "id": 157, "nombre": "Veterinario" },
  { "id": 158, "nombre": "Vigilante" },
  { "id": 159, "nombre": "Webmaster" },
  { "id": 160, "nombre": "Yesero" },

  { "id": 161, "nombre": "Youtuber" },
  { "id": 162, "nombre": "Zoologo" },

  { "id": 163, "nombre": "Operario industrial" },
  { "id": 164, "nombre": "Calderista" },
  { "id": 165, "nombre": "Tapicero" },
  { "id": 166, "nombre": "Maquinista ferroviario" },
  { "id": 167, "nombre": "Acompañante terapéutico" },

  { "id": 168, "nombre": "Fonoaudiólogo" },
  { "id": 169, "nombre": "Paramédico" },
  { "id": 170, "nombre": "Biotecnólogo" },
  { "id": 171, "nombre": "Técnico en refrigeración" },
  { "id": 172, "nombre": "Operador de call center" },

  { "id": 173, "nombre": "Auditor" },
  { "id": 174, "nombre": "Auxiliar de farmacia" },
  { "id": 175, "nombre": "Consultor" },
  { "id": 176, "nombre": "Ilustrador" },
  { "id": 177, "nombre": "Maquillador" },

  { "id": 178, "nombre": "Camarógrafo" },
  { "id": 179, "nombre": "Guionista" },
  { "id": 180, "nombre": "Locutor comercial" },
  { "id": 181, "nombre": "Operador de sonido" },
  { "id": 182, "nombre": "Técnico en luces" },

  { "id": 183, "nombre": "Arqueólogo" },
  { "id": 184, "nombre": "Meteorólogo" },
  { "id": 185, "nombre": "Sociólogo" },
  { "id": 186, "nombre": "Relaciones públicas" },
  { "id": 187, "nombre": "Piloto comercial" },

  { "id": 188, "nombre": "Desarrollador mobile" },
  { "id": 189, "nombre": "QA Tester" },
  { "id": 190, "nombre": "DevOps" },
  { "id": 191, "nombre": "Científico de datos" },
  { "id": 192, "nombre": "Product Manager" },

  { "id": 193, "nombre": "Scrum Master" },
  { "id": 194, "nombre": "Game Designer" },
  { "id": 195, "nombre": "Ingeniero agrónomo" },
  { "id": 196, "nombre": "Técnico forestal" },
  { "id": 197, "nombre": "Electricista industrial" },

  { "id": 198, "nombre": "Herrero" },
  { "id": 199, "nombre": "Fundidor" },
  { "id": 200, "nombre": "Grabador láser" },
  { "id": 201, "nombre": "Marmolero" },
  { "id": 202, "nombre": "Vidriero" },

  { "id": 203, "nombre": "Operador de grúa" },
  { "id": 204, "nombre": "Chofer de camión" },
  { "id": 205, "nombre": "Auxiliar de logística" },
  { "id": 206, "nombre": "Estibador" },
  { "id": 207, "nombre": "Mozo de almacén" },

  { "id": 208, "nombre": "Capataz" },
  { "id": 209, "nombre": "Supervisor" },
  { "id": 210, "nombre": "Encargado de depósito" },
  { "id": 211, "nombre": "Cobrador de peaje" },
  { "id": 212, "nombre": "Atención al cliente" },

  { "id": 213, "nombre": "Carretillero" },
  { "id": 214, "nombre": "Ingeniero hidráulico" },
  { "id": 215, "nombre": "Paisajista" },
  { "id": 216, "nombre": "Podador" },
  { "id": 217, "nombre": "Guardaparque" },

  { "id": 218, "nombre": "Capitán de barco" },
  { "id": 219, "nombre": "Marinero" },
  { "id": 220, "nombre": "Técnico aeronáutico" },
  { "id": 221, "nombre": "Operador de drones" },
  { "id": 222, "nombre": "Instructor" },

  { "id": 223, "nombre": "Barman" },
  { "id": 224, "nombre": "Sommelier de café" },
  { "id": 225, "nombre": "Cocinero industrial" },
  { "id": 226, "nombre": "Ayudante de cocina" },
  { "id": 227, "nombre": "Encargado de restaurante" },

  { "id": 228, "nombre": "Escenógrafo" },
  { "id": 229, "nombre": "Carpintero metálico" },
  { "id": 230, "nombre": "Restaurador" },
  { "id": 231, "nombre": "Anticuario" },
  { "id": 232, "nombre": "Ebanista" },

  { "id": 233, "nombre": "Taquígrafo" },
  { "id": 234, "nombre": "Criminólogo" },
  { "id": 235, "nombre": "Criptoanalista" },
  { "id": 236, "nombre": "Forense" },
  { "id": 237, "nombre": "Archivista" },

  { "id": 238, "nombre": "Tornero fresador" },
  { "id": 239, "nombre": "Operador CNC" },
  { "id": 240, "nombre": "Técnico en telecomunicaciones" },
  { "id": 241, "nombre": "Técnico en energía solar" },
  { "id": 242, "nombre": "Técnico en energía eólica" },

  { "id": 243, "nombre": "Instalador de aire acondicionado" },
  { "id": 244, "nombre": "Escaparatista" },
  { "id": 245, "nombre": "Vendedor telefónico" },
  { "id": 246, "nombre": "Consultor SEO" },
  { "id": 247, "nombre": "Administrador de base de datos" },

  { "id": 248, "nombre": "Ingeniero biomédico" },
  { "id": 249, "nombre": "Acuicultor" },
  { "id": 250, "nombre": "Oceanógrafo" }
]
